# Default values for helm-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: core-blue-green

replicaCount: 2

revisionHistoryLimit: 3

image:
  repository: core.hr.172.22.11.16.nip.io/library/bookinfo-core
  tag: v0.0.5
  # tag: green

service:
  port: 8080
  targetPort: 8080

configMap:
  name: config-ops
